export { default as FormSection } from '@/components/auth/Form'
export { default as FormBlock } from '@/components/auth/Block'
export { default as FormStatus } from '@/components/auth/Status'
export { default as FormText } from '@/components/auth/Text'
export { default as AuthDivider } from '@/components/auth/Divider'
export { default as FormGroup } from '@/components/auth/Group'