export { default as BookmarksAll } from '@/views/_bookmarks/All'
export { default as BookmarksUsers } from '@/views/_bookmarks/Users'
export { default as BookmarksEntries } from '@/views/_bookmarks/Entries'
export { default as BookmarksComments } from '@/views/_bookmarks/Comments'
export { default as BookmarksFeeds } from '@/views/_bookmarks/Feeds'
